[package]
name = "nidrs-macro"
version = "0.0.1"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "a nidrs macro."
edition = "2021"
keywords = ["nidrs"]
categories = [
  "macros",
]
homepage = "https://github.com/nidrs/nidrs.git"
repository = "https://github.com/nidrs/nidrs.git"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.79"
syn = { version = "2.0.53", features = ["full"] }
quote = "1.0.35"
once_cell = "1.19.0"
