[workspace]
members = [
  "packages/*",
  "examples/*",
  "scripts/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://github.com/nidrs/nidrs.git"
repository = "https://github.com/nidrs/nidrs.git"
license = "MIT"

[workspace.dependencies]
nidrs = { path = "packages/nidrs", version = "*" }
nidrs-extern = { path = "packages/nidrs-extern", version = "*" }
nidrs-macro = { path = "packages/nidrs-macro", version = "*" }
nidrs-diesel = { path = "packages/nidrs-diesel", version = "*" }
