[workspace]
members = [
  "packages/*",
  "examples/*",
]
resolver = "2"

[workspace.package]
version = "0.0.5"
edition = "2021"
publish = false

[workspace.dependencies]
nidrs = { path = "packages/nidrs" }
nidrs-extern = { path = "packages/nidrs-extern" }
nidrs-macro = { path = "packages/nidrs-macro" }