[workspace]
members = [
  "packages/*",
  "examples/*",
]
resolver = "2"

[workspace.package]
version = "0.0.7"
edition = "2021"
publish = false
homepage = "https://github.com/nidrs/nidrs.git"
repository = "https://github.com/nidrs/nidrs.git"
license = "MIT"

[workspace.dependencies]
nidrs = { path = "packages/nidrs", version = "0.0.7" }
nidrs-extern = { path = "packages/nidrs-extern", version = "0.0.7" }
nidrs-macro = { path = "packages/nidrs-macro", version = "0.0.7" }
