from_latest_tag = true
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = ["main", "release/**"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = [
    "git add Cargo.lock && git commit -m 'chore: bump to {{version}}'",
]
# pre_package_bump_hooks = []
# post_package_bump_hooks = []
tag_prefix = "v"

monorepo_version_separator = "-"
pre_package_bump_hooks = [
    "echo 'upgrading {{package}}' to {{version}}",
    "cargo set-version {{version}} -p {{package}}",
]
post_package_bump_hooks = [
    "echo 'package {{package}}'",
    "cargo package --allow-dirty -p {{package}}",
    "echo 'publishing {{package}}'",
    "cargo publish --registry crates-io -p {{package}}",
]

[git_hooks]
[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
"""
[git_hooks.pre-commit]
script = """#!/bin/sh
cargo clippy --fix --allow-staged --allow-dirty
STAGED_CHANGES=$(git diff --cached --name-only --diff-filter=ACM | grep '\\.rs$')

if [ -n "$STAGED_CHANGES" ]; then
    echo "Running cargo fmt on staged changes..."
    for FILE in $STAGED_CHANGES; do
        cargo fmt -- "$FILE"
        git add "$FILE"
    done
    echo "cargo fmt completed successfully."
fi

exit 0
# git add .
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "nidrs"
owner = "nidrs"
authors = [
  { signature = "Lydanne", username = "Lyda" },
  { signature = "WumaCoder", username = "WumaCoder" },
  { signature = "刘欢", username = "WumaCoder" },
]
[bump_profiles]

[packages]
nidrs-valid = { path = "packages/nidrs-valid" }
nidrs-valid-macro = { path = "packages/nidrs-valid-macro" }
nidrs-extern = { path = "packages/nidrs-extern" }
nidrs-macro = { path = "packages/nidrs-macro" }
nidrs-diesel = { path = "packages/nidrs-diesel" }
nidrs = { path = "packages/nidrs" }
macro_args = { path = "libs/macro_args" }
