from_latest_tag = true
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks]
[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
"""
[git_hooks.pre-commit]
script = """#!/bin/sh
cargo clippy --fix --allow-dirty --allow-staged && cargo fmt -v --all
git add .
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "nidrs"
owner = "nidrs"
authors = [
  { signature = "WumaCoder", username = "WumaCoder" },
  { signature = "刘欢", username = "WumaCoder" },
]
[bump_profiles]

[packages]
