[package]
name = "nidrs-extern"
version = "0.0.3"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "Nidrs external library."
edition = "2021"
keywords = ["nidrs", "axum", "http", "web", "framework"]
categories = [
    "network-programming",
    "asynchronous",
    "web-programming::http-server",
    "web-programming::websocket"
]
homepage = "https://github.com/nidrs/nidrs.git"
repository = "https://github.com/nidrs/nidrs.git"
license = "MIT"

[dependencies]
axum = { version = "0.7.4", features = ["ws"] }
axum-extra = { version = "0.9.2", features = ["typed-header", "typed-routing"] }
tokio = {version = "1.36.0", features = ["full"]}
tower = "0.4.13"
colored = "2"
anyhow = "1.0.82"
thiserror = "1.0.58"
serde_json = "1.0.115"
serde = "1.0.197"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
