[package]
name = "nidrs"
version = "0.0.8"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "Nidrs is a web framework based on axum and tokio."
keywords = ["nidrs", "axum", "http", "web", "framework"]
categories = [
    "network-programming",
    "asynchronous",
    "web-programming::http-server",
    "web-programming::websocket"
]
publish = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
nidrs-macro = { workspace = true }
nidrs-extern = { workspace = true }

serde_json = "1.0.115"
serde = {version = "1.0.197", features = ["derive"]}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
