[package]
name = "nidrs"
version = "0.0.1"
authors = ["WumaCoder <wumacoder@gmail.com>"]
edition = "2021"
keywords = ["nidrs", "tokio", "axum", "http", "web", "framework", "async"]
categories = [
    "network-programming",
    "asynchronous",
    "web-programming::http-server",
    "web-programming::websocket"
]
homepage = "https://github.com/nidrs/nidrs.git"
repository = "https://github.com/nidrs/nidrs.git"
license = "MIT"

[dependencies]
axum = { version = "0.7.4", features = ["ws"] }
axum-extra = { version = "0.9.2", features = ["typed-header", "typed-routing"] }
tokio = {version = "1.36.0", features = ["full"]}
tower = "0.4.13"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
