[package]
name = "nidrs"
version = "0.0.3"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "Nidrs is a web framework based on axum and tokio."
edition = "2021"
keywords = ["nidrs", "axum", "http", "web", "framework"]
categories = [
    "network-programming",
    "asynchronous",
    "web-programming::http-server",
    "web-programming::websocket"
]
homepage = "https://github.com/nidrs/nidrs.git"
repository = "https://github.com/nidrs/nidrs.git"
license = "MIT"

[dependencies]
nidrs-extern = { path = "../nidrs-extern" }
nidrs-macro = { path = "../nidrs-macro" }
once_cell = "1.19.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
