[package]
name = "nidrs-valid"
version = "0.0.1"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "Nidrs dto valid library."
keywords = ["nidrs", "axum", "http", "web", "framework"]
categories = ["network-programming", "asynchronous", "web-programming::http-server", "web-programming::websocket"]
publish = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
nidrs-valid-macro = { workspace = true }
serde_json = "1.0.115"
serde = "1.0.197"
thiserror = "1.0.58"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
